mysite/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('personal.urls')),
]

personal/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^projects/$', views.projects, name='projects'),
    re_path(r'^blog/$', views.blog, name='blog'),
    re_path(r'^posts/(?P<pk>\d+)/(?P<slug>[\w-]+)/?$', views.post, name='post'),
    re_path(r'^media/$', views.MediaView.as_view(), name='media'),
    re_path(r'^delete/media/(?P<pk>\d+)/?$', views.delete, name='deleteMedia'),
    re_path(r'^logout/?$', views.logoutView, name='logout'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/models.py
from django.db import models
from taggit.managers import TaggableManager
from taggit.models import Tag
from django.utils.timezone import datetime
from ckeditor.fields import RichTextField
from django.utils.text import slugify


class Bio(models.Model):
    cache_version = models.CharField(max_length=10, default="1.0.0")
    name = models.CharField(max_length=2000, default="Your Name")
    initials = models.CharField(max_length=2000, blank=True, null=True)
    title = models.CharField(max_length=2000, blank=True, null=True)
    greeting = models.CharField(max_length=2000, blank=True, null=True)
    screenshot_url = models.CharField(max_length=2000, blank=True, null=True)
    favicon_url = models.CharField(max_length=2000, blank=True, null=True)
    siteicon_url = models.CharField(max_length=2000, blank=True, null=True)
    email = models.CharField(max_length=2000, blank=True, null=True)
    phone_number = models.CharField(max_length=2000, blank=True, null=True)
    employment = models.CharField(max_length=2000, blank=True, null=True)
    location = models.CharField(max_length=2000, blank=True, null=True)
    github_url = models.CharField(max_length=2000, blank=True, null=True)
    linkedin_url = models.CharField(max_length=2000, blank=True, null=True)
    youtube_url = models.CharField(max_length=2000, blank=True, null=True)
    facebook_url = models.CharField(max_length=2000, blank=True, null=True)
    twitter_url = models.CharField(max_length=2000, blank=True, null=True)
    resume_url = models.CharField(max_length=2000, blank=True, null=True)
    about_me = RichTextField(blank=True, null=True)
    show_about_buttons = models.BooleanField(default=True)
    announcement = RichTextField(blank=True, null=True)
    website_repo_url = models.CharField(max_length=2000, blank=True, null=True)

    def __str__(self):
        return self.name


class File(models.Model):
    name = models.CharField(max_length=2000, null=True, blank=True)
    file = models.FileField()
    date_uploaded = models.DateTimeField(default=datetime.now)

    def __str__(self):
        if (not self.name):
            return str(self.file)
        else:
            return self.name


class Post(models.Model):
    title = models.CharField(max_length=2000)
    slug = models.CharField(max_length=2000, blank=True)
    category = models.CharField(max_length=50, choices=[('project', 'Project'), ('blog', 'Blog')], default="project")
    subtitle = models.CharField(max_length=2000, blank=True)
    visible = models.BooleanField(default=True)
    show_on_homepage = models.BooleanField(default=False)
    screenshot = models.CharField(max_length=2000, blank=True)
    gradient = models.CharField(max_length=2000, blank=True)
    fallback_background = models.CharField(max_length=2000, blank=True)
    screenshot_credit = models.CharField(max_length=2000, blank=True)
    short_description = RichTextField(blank=True)
    primary_button_text = models.CharField(max_length=50, default="View Post")
    tags = TaggableManager(blank=True)
    body = RichTextField()
    date_posted = models.DateTimeField(default=datetime.now)
    date_edited = models.DateTimeField(blank=True, null=True)
    display_posted = models.BooleanField(default=False)
    display_edited = models.BooleanField(default=False)
    files = models.ManyToManyField(File, blank=True)

    def __str__(self):
        if (self.visible == False):
            return '(Invisible) ' + self.title
        return self.title

    def save(self, *args, **kwargs):
        self.date_edited = datetime.now()
        if not self.slug:
            self.slug = slugify(self.title)
        self.slug = slugify(self.slug)
        super(Post, self).save(*args, **kwargs)


class LinkPost(models.Model):
    title = models.CharField(max_length=2000)
    category = models.CharField(max_length=50, choices=[('project', 'Project'), ('blog', 'Blog')], default="project")
    subtitle = models.CharField(max_length=2000, blank=True)
    visible = models.BooleanField(default=True)
    show_on_homepage = models.BooleanField(default=False)
    screenshot = models.CharField(max_length=2000, blank=True)
    gradient = models.CharField(max_length=2000, blank=True)
    fallback_background = models.CharField(max_length=2000, blank=True)
    short_description = RichTextField(blank=True)
    primary_button_text = models.CharField(max_length=50, default="Visit Link")
    primary_button_link = models.CharField(max_length=2000, blank=True)
    secondary_button_text = models.CharField(max_length=50, blank=True)
    secondary_button_link = models.CharField(max_length=2000, blank=True)
    tags = TaggableManager(blank=True)
    date_posted = models.DateTimeField(default=datetime.now)
    date_edited = models.DateTimeField(blank=True, null=True)
    display_posted = models.BooleanField(default=True)
    display_edited = models.BooleanField(default=False)

    def __str__(self):
        if (self.visible == False):
            return '(Invisible) ' + self.title
        return self.title

    def save(self, *args, **kwargs):
        self.date_edited = datetime.now()
        super(LinkPost, self).save(*args, **kwargs)

personal/forms.py
from django import forms
from personal.models import File
from taggit.forms import TagWidget

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name', 'file']

personal/views.py
import os
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponseNotFound, HttpResponseRedirect
from django.db.models import Q
from django.views.generic import UpdateView
from django.contrib.auth import logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from personal.models import Post, LinkPost, File
from .forms import FileForm
from itertools import chain
import operator


def index(request):
    if (request.user.is_superuser):
        project_post_count = Post.objects.all().filter(Q(category='project')).count() + LinkPost.objects.all().filter(Q(category='project')).count()
        project_posts = Post.objects.all().filter(Q(show_on_homepage=True, category='project'))
        project_linkposts = LinkPost.objects.all().filter(Q(show_on_homepage=True, category='project'))

        blog_post_count = Post.objects.all().filter(Q(category='blog')).count() + LinkPost.objects.all().filter(Q(category='blog')).count()
        blog_posts = Post.objects.all().filter(Q(show_on_homepage=True, category='blog'))
        blog_linkposts = LinkPost.objects.all().filter(Q(show_on_homepage=True, category='blog'))

    else:
        project_post_count = Post.objects.all().filter(Q(category='project', visible=True)).count() + LinkPost.objects.all().filter(Q(category='project')).count()
        project_posts = Post.objects.all().filter(Q(show_on_homepage=True, category='project', visible=True))
        project_linkposts = LinkPost.objects.all().filter(Q(show_on_homepage=True, category='project', visible=True))

        blog_post_count = Post.objects.all().filter(Q(category='blog', visible=True)).count() + LinkPost.objects.all().filter(Q(category='blog')).count()
        blog_posts = Post.objects.all().filter(Q(show_on_homepage=True, category='blog', visible=True))
        blog_linkposts = LinkPost.objects.all().filter(Q(show_on_homepage=True, category='blog', visible=True))

    project_posts = sorted(
        chain(project_posts, project_linkposts),
        key=operator.attrgetter('date_posted'),
        reverse=True
    )

    blog_posts = sorted(
        chain(blog_posts, blog_linkposts),
        key=operator.attrgetter('date_posted'),
        reverse=True
    )

    return render(
        request,
        'personal/index.html',
        {
            'project_posts': project_posts,
            'more_project_posts': project_post_count > len(project_posts),
            'blog_posts': blog_posts,
            'more_blog_posts': blog_post_count > len(blog_posts)
        },
    )


def projects(request):
    if (request.user.is_superuser):
        posts = Post.objects.all().filter(Q(category='project'))
        linkposts = LinkPost.objects.all().filter(Q(category='project'))
    else:
        posts = Post.objects.all().filter(Q(category='project', visible=True))
        linkposts = LinkPost.objects.all().filter(Q(category='project', visible=True))

    posts = sorted(
        chain(posts, linkposts),
        key=operator.attrgetter('date_posted'),
        reverse=True
    )

    paginator = Paginator(posts, per_page=3)

    page = request.GET.get('p')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'personal/projects.html',
        {'project_posts': posts}
    )

def blog(request):
    if (request.user.is_superuser):
        posts = Post.objects.all().filter(Q(category='blog'))
        linkposts = LinkPost.objects.all().filter(Q(category='blog'))
    else:
        posts = Post.objects.all().filter(Q(category='blog', visible=True))
        linkposts = LinkPost.objects.all().filter(Q(category='blog', visible=True))

    posts = sorted(
        chain(posts, linkposts),
        key=operator.attrgetter('date_posted'),
        reverse=True
    )

    paginator = Paginator(posts, per_page=3)

    page = request.GET.get('p')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'personal/blog.html',
        {'blog_posts': posts}
    )

def delete(request, pk):
    if (not request.user.is_superuser):
        return HttpResponseForbidden()

    name = request.resolver_match.view_name

    if (name == 'deleteMedia'):
        media = File.objects.all().get(id=pk)

        if (media is not None):
            media.delete()

        return HttpResponseRedirect('/media')
    else:
        return HttpResponseRedirect('/')


def logoutView(request):
    logout(request)
    return redirect('/')


def post(request, pk, slug):
    try:
        post = Post.objects.all().get(id=int(pk))
    except:
        return HttpResponseNotFound()

    if (post == None):
        return HttpResponseNotFound()
    else:
        if (post.visible == True or request.user.is_superuser):
            if slug != post.slug:
                return redirect('post', pk=post.pk, slug=post.slug, permanent=True)
            else:
                return render(request, 'personal/post.html', {'post': post})
        else:
            return HttpResponseForbidden()


class MediaView(UpdateView):
    form_class = FileForm
    model = File
    template_name = 'personal/media.html'

    def get(self, request):
        if (request.user.is_superuser):
            files = File.objects.all().order_by("-date_uploaded")

            paginator = Paginator(files, per_page=20)

            page = request.GET.get('p')
            try:
                files = paginator.page(page)
            except PageNotAnInteger:
                files = paginator.page(1)
            except EmptyPage:
                files = paginator.page(paginator.num_pages)

            form = self.form_class(None)

            return render(
                request,
                self.template_name,
                {
                    'form': form,
                    'posts': files,
                    'paginator': paginator,
                }
            )
        else:
            return HttpResponseForbidden()

    def post(self, request):

        if (not request.user.is_superuser):
            return HttpResponseForbidden()

        form = self.form_class(request.POST, request.FILES)

        if (form.is_valid()):
            name = form.cleaned_data['name']
            file = form.cleaned_data['file']

            media = form.save(commit=False)

            if (not name):
                media.name = name
            media.file = file

            media = form.save()

            return redirect('/media')
        else:
            return HttpResponseNotFound()

personal/templates/personal/blog.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block title %}Blog{% endblock %}
{% block pagename %}Blog{% endblock %}

{% block content %}

{% include "personal/includes/navbar.html" with active_link="blog" %}


<div class="background-wrapper is-dark flex-grow">
    <div class="container">
        {% include "personal/includes/blog_list.html" %}
    </div>
    <section class="section pt-0">
        {% include "personal/includes/pagination.html" with bottom=True %}
    </section>
</div>

{% endblock %}

personal/templates/personal/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block no_title %}{% block title %}{% endblock %} - {% endblock %}{{ bio.name }}</title>
    {% load static %}

    <meta name="viewport"
        content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">

    {% if bio.favicon_url %}<link rel="shortcut icon" type="image/x-icon" href="{{bio.favicon_url}}">{% endif %}

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.7.2/css/all.css"
        integrity="sha384-nRgPTkuX86pH8yjPJUAFuASXQSSl2/bBUiNV47vSYpKFxHJhbcrGnmlYpYJMeD7a" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css"
        integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}?v={{bio.cache_version}}" type="text/css" />

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap');
    </style>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"
        integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}?v={{bio.cache_version}}"></script>
</head>

{% load personal_extras %}

<body>
    <div class="site-wrapper">
        {% if bio.announcement %}
        <div class="container">
            <div class="notification announcement">{{ bio.announcement|safe }}</div>
        </div>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    {% include "personal/includes/footer.html" %}
</body>

</html>

personal/templates/personal/index.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block no_title %}{% endblock %}
{% block pagename %}Home{% endblock %}

{% block content %}



{% include "personal/includes/navbar.html" with active_link="home" %}

<div class="container">
    <section id="about-section" class="section">
        <div id="about">
            <div class="shelf is-half">
                <div class="shelf-content">
                    {% if bio.title %}<h1 class="title is-spaced">{{ bio.title|safe }}</h1>{% endif %}
                    {% if bio.greeting %}<span class="subtitle">{{ bio.greeting }}</span>{% endif %}
                    <div class="mb-4">{{ bio.about_me|safe }}</div>
                    {% if bio.location %}
                    <p class="icon-text mb-4">
                        <span class="fa-stack mr-1">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fas fa-map-marker-alt fa-stack-1x fa-inverse"></i>
                        </span>
                        {{ bio.location|safe }}
                    </p>
                    {% endif %}
                    {% if bio.employment %}
                    <p class="icon-text">
                        <span class="fa-stack mr-1">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fas fa-briefcase fa-stack-1x fa-inverse"></i>
                        </span>
                        {{ bio.employment|safe }}
                    </p>
                    {% endif %}
                </div>
                {% if bio.screenshot_url %}
                <div class="shelf-image fade-in">
                    <figure class="image has-shadow">
                        <img id="face" src="{{ bio.screenshot_url }}">
                    </figure>
                </div>
                {% endif %}
            </div>   
            {% if bio.show_about_buttons %}
                {% if bio.resume_url %}
                <a class="button is-dark is-medium is-block" href="{{ bio.resume_url }}" target="_blank"><i class="far fa-list-alt"></i> Resume</a>
                {% endif %}
            {% endif %}
        </div>
    </section>
</div>
{% if project_posts or blog_posts %}
<div class="background-wrapper is-dark flex-grow">
    <div class="container">
        {% if project_posts %}
            {% include "personal/includes/projects_list.html" %}
            <!-- {% if more_project_posts %}
            <section class="section pt-0">
                <a class="button is-dark is-medium is-block" href="/projects/">View All Posts</a>
            </section>
            {% endif %} -->
        {% endif %}
        {% if blog_posts %}
            {% include "personal/includes/blog_list.html" %}
            <!-- {% if more_blog_posts %}
            <section class="section pt-0">
                <a class="button is-dark is-medium is-block" href="/blog/">View All Posts</a>
            </section>
            {% endif %} -->
        {% endif %}
    </div>
</div>
{% endif %}

{% endblock %}

personal/templates/personal/media.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block title %}Media{% endblock %}
{% block pagename %}Media{% endblock %}

{% block content %}

{% include "personal/includes/navbar.html" %}


<div class="container">
    <section class="section">
        <h1>Media</h1>
        <form class="upload-form" role="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label class="label">Alias</label>
                <div class="control">
                    <input class="input" type="text" name="name" maxlength="256" id="id_name" placeholder="Enter alias...">
                </div>
            </div>
            <div class="field">
                <div class="file has-name is-fullwidth">
                    <label class="file-label">
                        <input class="file-input" type="file" name="file" required="" id="id_file">
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Choose a file…
                            </span>
                        </span>
                        <span class="file-name"></span>
                    </label>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-dark" type="submit">Upload</button>
                </div>
            </div>
        </form>
    </section>
    <section class="section">
        <div class="columns is-multiline">
            {% for file in posts %}
            <div
                class="column 
            is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd is-pulled-left"
                style="word-break: break-all;"
            >
                <a href="/delete/media/{{ file.id }}" class="delete" style="float: right;">Delete</a>
                <a class="copy-to-clipboard" data-url="{{ file.file.url }}">
                    {{ file|file_to_icon }}
                    <p>Copy URL to clipboard</p>
                </a>
                <a href="{{ file.file.url }}" target="_blank">{{ file }}</a>
            </div>
            {% empty %}
            <p>Nothing here.</p>
            {% endfor %}
        </div>
        {% include "personal/includes/pagination.html" with bottom=True %}
    </section>
</div>

{% endblock %}

personal/templates/personal/post.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block title %}{{ post.title }}{% endblock %}
{% block pagename %}Post{% endblock %}

{% block content %}

{% include "personal/includes/navbar.html" with active_link=post.category has_progress=True  %}
<div class="background-wrapper is-dark">
    <div class="container">
        <section class="post-header section">
            <div class="subtitle">{{ post.subtitle|default:post.category }}</div>
            <h1 class="post-title title">
                {% if not post.visible %}
                <span class="icon has-text-danger"><i class="fa fa-eye-slash" aria-hidden="true"></i></span>
                {% endif %}
                {{ post.title }}
            </h1>
            {% if post.display_posted %}
            <p class="date"><span class="icon is-color"><i
                        class="fas fa-calendar-alt"></i></span>{{ post.date_posted|date:"F j, Y, g:i A" }}{% if post.display_edited %}<span
                    class="icon is-color"><i class="fas fa-pencil-alt"></i></span>{{ post.date_edited|date:"F j, Y, g:i A" }}{% endif %}</p>
            {% endif %}
            <div class="tags">
                {% for tag in post.tags.all %}
                <span class="tag is-black">{{ tag.name }}</span>
                {% endfor %}
            </div>
            <figure class="image has-shadow">
                <img src="{{ post.screenshot }}">
            </figure>
            {% if post.screenshot_credit %}<p class="screenshot-credit">{{ post.screenshot_credit|safe }}</p>{% endif %}
        </section>
    </div>
</div>
<div class="container">
    <section class="section">
        <div class="post-container">{{ post.body|safe }}</div>

        {% if post.files.count is not 0 %}
        <h2 class="mb-1">{{ post.files.count }} Attachment{% if post.files.count is not 1 %}s{% endif %}</h2>
        <article class="panel is-primary">
            {% for file in post.files.all %}
            <div class="panel-block">
                {{ file|file_to_icon }}
                <a href="{{ file.file.url }}">
                    <span class="ml-2">{{ file }}</span>
                </a>
            </div>
            {% endfor %}
        </article>
        {% endif %}

        {% if user.is_superuser %}
        <p><a class="button is-dark" href="/admin/personal/post/{{ post.id }}/change">Edit Post</a></p>
        <br/>
        {% endif %}

        <a href="/{{ post.category }}{% if post.category == 'project' %}s{% endif %}" class="button is-dark">Return to {{ post.get_category_display }}{% if post.category == 'project' %}s{% endif %}</a>
    </section>
</div>
{% endblock %}

personal/templates/personal/posts.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block title %}Portfolio{% endblock %}
{% block pagename %}Portfolio{% endblock %}

{% block content %}

{% include "personal/includes/navbar.html" with active_link="post" %}


<div class="background-wrapper is-dark">
    <div class="container">
        {% include "personal/includes/posts_list.html" %}
    </div>
    <section class="section pt-0">
        {% include "personal/includes/pagination.html" with bottom=True %}
    </section>
</div>

{% endblock %}

personal/templates/personal/projects.html
{% extends "personal/header.html" %}

{% load personal_extras %}

{% block title %}Projects{% endblock %}
{% block pagename %}Projects{% endblock %}

{% block content %}

{% include "personal/includes/navbar.html" with active_link="project" %}


<div class="background-wrapper is-dark flex-grow">
    <div class="container">
        {% include "personal/includes/projects_list.html" %}
    </div>
    <section class="section pt-0">
        {% include "personal/includes/pagination.html" with bottom=True %}
    </section>
</div>

{% endblock %}